### ISSUE TITLE
PHP 7 Not Compiling with OpenSSL Support - OS X 10.11

### ISSUE THREAD

**Issue by dtdpro** [pbougie/mac-dev-env#17]
The config option listed is --with-openssl-dir which is incorrect, it should be --with-openssl (http://php.net/manual/en/openssl.installation.php). However, once corrected, PHP is not compiling with the latest version of OpenSSL.  It will compile with (out of support) OpenSSL 0.9.8 branch.

**Comment by dtdpro** [comment]
This produces the error:

`Undefined symbols for architecture x86_64:
  "_PKCS5_PBKDF2_HMAC", referenced from:
      _zif_openssl_pbkdf2 in openssl.o
  "_SSL_CTX_set_alpn_protos", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_SSL_CTX_set_alpn_select_cb", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_SSL_get0_alpn_selected", referenced from:
      _php_openssl_sockop_set_option in xp_ssl.o
  "_SSL_select_next_proto", referenced from:
      _server_alpn_callback in xp_ssl.o
  "_TLSv1_1_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_1_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_client_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
  "_TLSv1_2_server_method", referenced from:
      _php_openssl_setup_crypto in xp_ssl.o
ld: symbol(s) not found for architecture x86_64
`

**Comment by pbougie** [comment]
Sorry for the delay but I was on vacation when you posted this issue. I have rectified the problem. See commit https://github.com/pbougie/mac-dev-env/commit/f749d07b8b7eee69e4c6223646e9141476670267.
